print("test1")
print("test2")
print("test3")
print("weird line not matching pattern")
print("test2")
print("test3")
print("test5")
print("weird line not matching pattern")
print("test2")
print("test3")
print("test5")
